kind: role
metadata:
  description: RBAC base SSH access role for Technical Certification
  name: tc-ssh
spec:
  allow:
    logins:
    - teleport-noroot
    node_labels:
      '*': '*'
  deny:
    host_sudoers:
    - '*'
    - 'ALL=(ALL) NOPASSWD: ALL'  
  options:
    cert_format: standard
    create_host_user_default_shell: /bin/bash
    create_host_user_mode: insecure-drop
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v8
